# config/packages/monolog.yaml
monolog:
    channels: ['db']
    handlers:
        dbHandler:
            channels: ['db']
            type: service
            id: monolog.dbHandler

#monolog:
#    channels: ['db']
#    handlers:
#        db:
#            channels: ['db']
#            type: service
#            id: monolog.db_handler