vich_uploader:
    db_driver: orm

    mappings:
        user_images:
            uri_prefix: '%app.path.logo%'
            upload_destination: '%kernel.project_dir%/public%app.path.logo%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
